name: aipsqs
description: "AI-Powered Smart Quiz System for Enhanced Learning"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core and Services
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7


  # Network
  http: ^1.4.0

  # State Management
  provider: ^6.1.2

  # Charts
  fl_chart: ^0.66.0

  # UI & Animation
  google_fonts: ^6.2.1
  animations: ^2.0.11
  flutter_spinkit: ^5.2.0

  # Date/Time Formatting
  intl: ^0.19.0

  # Secure Storage (optional, future use)
  flutter_secure_storage: ^9.1.1





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  