// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYPJxbpmIggouB6tNxtHVcuFPQekc6Psk',
    appId: '1:88102053412:web:48388cd1c7cbadfed45ab1',
    messagingSenderId: '88102053412',
    projectId: 'a7aipsqs',
    authDomain: 'a7aipsqs.firebaseapp.com',
    storageBucket: 'a7aipsqs.firebasestorage.app',
    measurementId: 'G-5Y5GPL8WKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8vDzoZi57hcSaeYhPmDbO4esGoSqg5E',
    appId: '1:88102053412:android:870cf3be92301a99d45ab1',
    messagingSenderId: '88102053412',
    projectId: 'a7aipsqs',
    storageBucket: 'a7aipsqs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrhNVEDNnNUSPAlFGO60UvMidSso8V9w4',
    appId: '1:88102053412:ios:e3377ed9a04d99bfd45ab1',
    messagingSenderId: '88102053412',
    projectId: 'a7aipsqs',
    storageBucket: 'a7aipsqs.firebasestorage.app',
    iosBundleId: 'com.example.aipsqs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrhNVEDNnNUSPAlFGO60UvMidSso8V9w4',
    appId: '1:88102053412:ios:e3377ed9a04d99bfd45ab1',
    messagingSenderId: '88102053412',
    projectId: 'a7aipsqs',
    storageBucket: 'a7aipsqs.firebasestorage.app',
    iosBundleId: 'com.example.aipsqs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYPJxbpmIggouB6tNxtHVcuFPQekc6Psk',
    appId: '1:88102053412:web:7d934eee47561dc7d45ab1',
    messagingSenderId: '88102053412',
    projectId: 'a7aipsqs',
    authDomain: 'a7aipsqs.firebaseapp.com',
    storageBucket: 'a7aipsqs.firebasestorage.app',
    measurementId: 'G-L6Z9MRDCX8',
  );
}
